name: Incorrect Page Content
description: Point out problems with the content
title: "[Page Content] "
labels: ["Content Bug / 页面内容有误", "help wanted / 需要帮助"]

body:
- type: markdown
  attributes:
    value: We welcome you to point out content errors to us! Please fill in the following form.
- type: checkboxes
  id: confirm
  attributes:
    label: Please Choose
    options:
    - label: I'm working on fixing this issue.
      required: false
    - label: I confirmed that there is no similar issue.
      required: true
- type: input
  id: page
  attributes:
    label: I am visiting this page
    description: It is recommended to bring a link to better locate the problem.
    placeholder: https://github.com/ruyisdk/support-matrix/blob/main/BPI-F3/README.md
  validations:
    required: true
- type: textarea
  id: problem
  attributes:
    label: I found this problem on the page
    placeholder: I found this does not exist.
  validations:
    required: true
